#ifndef ALGAE_PANEL_REMOTE_CODES_H
#define ALGAE_PANEL_REMOTE_CODES_H


#define IRREMOTE_DOWN 58
#define IRREMOTE_UP 57
#define IRREMOTE_LEFT 59
#define IRREMOTE_RIGHT 60
#define IRREMOTE_CENTRE 61
#define IRREMOTE_OFF 21
#define IRREMOTE_MENU 41
#define  IRREMOTE_BACK 67
 

#define IRREMOTE_RED 103

#define IRREMOTE_BLUE 102

#define IRREMOTE_GREEN 104

#define IRREMOTE_YELLOW 105
#endif 